name: video_trimmer
description: A Flutter package for trimming videos. This supports retrieving, trimming, and storage of trimmed video files to the file system.
version: 3.0.1
homepage: https://github.com/sbis04/video_trimmer

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  video_player: ^2.9.2
  ffmpeg_kit_flutter:
    git:
      url: https://github.com/mohamedArafa25/ffmpeg-kit.git
      ref: main
      path: flutter/flutter
#  flutter_video_thumbnail_plus: ^1.0.5
  video_thumbnail:
    git:
      url: https://github.com/mohamedArafa25/video_thumbnail.git
      ref: master
  path_provider: ^2.1.5
  intl: ^0.20.2
  path: ^1.9.1
  transparent_image: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  lints: ^4.0.0

flutter:
